name 'setupweb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures setupweb'
long_description IO.read(File.join(File.dirname(__FILE__),'README.md'))
version '0.1.0'
chef_version '>= 13.0'
supports 'windows'
supports 'linux'
